import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadLocalesFromFile } from "lino-i18n/loaders";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const catalogPath = path.join(projectRoot, "src/lib/i18n/translations/catalog.lino");
const outputDir = path.join(projectRoot, "src/lib/i18n/generated");
const indexPath = path.join(outputDir, "catalogues.ts");

function assertSafeLocale(locale: string): asserts locale is string {
  if (!/^[a-z0-9-]+$/i.test(locale)) {
    throw new Error(`Locale '${locale}' cannot be used as a generated file name.`);
  }
}

async function main() {
  const loaded = await loadLocalesFromFile(catalogPath, {
    compatibilityAliases: ["collapseTail", "parentLabel"],
  });

  const catalogues = Object.fromEntries(
    loaded
      .filter(({ locale }) => Boolean(locale))
      .map(({ locale, translations }) => [locale, translations])
  );

  const englishKeys = Object.keys(catalogues.en ?? {}).sort();

  if (englishKeys.length === 0) {
    throw new Error("The i18n catalog must include a non-empty 'en' locale.");
  }

  for (const [locale, translations] of Object.entries(catalogues)) {
    const keys = Object.keys(translations).sort();
    const missing = englishKeys.filter((key) => !keys.includes(key));
    if (missing.length > 0) {
      throw new Error(
        `Locale '${locale}' is missing ${missing.length} translation keys: ${missing
          .slice(0, 10)
          .join(", ")}`
      );
    }
  }

  const locales = Object.keys(catalogues).sort();

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });

  for (const locale of locales) {
    assertSafeLocale(locale);
    const localeOutput = `// Generated by scripts/compile-i18n.ts from src/lib/i18n/translations/catalog.lino.\n// Do not edit this file directly.\n\nconst translations = ${JSON.stringify(
      catalogues[locale],
      null,
      2
    )} as const;\n\nexport default translations;\n`;

    await writeFile(path.join(outputDir, `${locale}.ts`), localeOutput);
  }

  const imports = locales
    .map((locale) => `import ${locale.replace(/-/g, "_")} from "./${locale}";`)
    .join("\n");
  const catalogueEntries = locales.map((locale) => `  ${JSON.stringify(locale)}: ${locale.replace(/-/g, "_")},`).join("\n");
  const indexOutput = `// Generated by scripts/compile-i18n.ts from src/lib/i18n/translations/catalog.lino.\n// Do not edit this file directly.\n\n${imports}\n\nexport const catalogues = {\n${catalogueEntries}\n} as const;\n\nexport type Locale = keyof typeof catalogues;\nexport type TranslationKey = keyof typeof catalogues.en;\n`;

  await writeFile(indexPath, indexOutput);

  console.log(
    `Compiled ${Object.keys(catalogues).length} locales and ${englishKeys.length} keys to ${path.relative(
      projectRoot,
      outputDir
    )}.`
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
