import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadLocalesFromFile } from "lino-i18n/loaders";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const catalogPath = path.join(projectRoot, "src/lib/i18n/translations/catalog.lino");
const outputPath = path.join(projectRoot, "src/lib/i18n/catalogues.ts");

async function main() {
  const loaded = await loadLocalesFromFile(catalogPath, {
    compatibilityAliases: ["collapseTail", "parentLabel"],
  });

  const catalogues = Object.fromEntries(
    loaded
      .filter(({ locale }) => Boolean(locale))
      .map(({ locale, translations }) => [locale, translations])
  );

  const englishKeys = Object.keys(catalogues.en ?? {}).sort();

  if (englishKeys.length === 0) {
    throw new Error("The i18n catalog must include a non-empty 'en' locale.");
  }

  for (const [locale, translations] of Object.entries(catalogues)) {
    const keys = Object.keys(translations).sort();
    const missing = englishKeys.filter((key) => !keys.includes(key));
    if (missing.length > 0) {
      throw new Error(
        `Locale '${locale}' is missing ${missing.length} translation keys: ${missing
          .slice(0, 10)
          .join(", ")}`
      );
    }
  }

  const output = `// Generated by scripts/compile-i18n.ts from src/lib/i18n/translations/catalog.lino.\n// Do not edit this file directly.\n\nexport const catalogues = ${JSON.stringify(catalogues, null, 2)} as const;\n\nexport type Locale = keyof typeof catalogues;\nexport type TranslationKey = keyof typeof catalogues.en;\n`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output);

  console.log(
    `Compiled ${Object.keys(catalogues).length} locales and ${englishKeys.length} keys to ${path.relative(
      projectRoot,
      outputPath
    )}.`
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
