#!/usr/bin/env npx tsx
/**
 * SatyaVera — Seed Legal Dictionary
 *
 * Creates 100 bilingual legal terms in Firestore.
 *
 * Usage:
 *   npx tsx scripts/seed-dictionary.ts [--dry-run] [--force]
 */

import { initializeApp, getApps, cert } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";
import * as dotenv from "dotenv";
dotenv.config();

if (getApps().length === 0) {
  const projectId = process.env.FIREBASE_ADMIN_PROJECT_ID || process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
  const clientEmail = process.env.FIREBASE_ADMIN_CLIENT_EMAIL;
  const privateKey = process.env.FIREBASE_ADMIN_PRIVATE_KEY?.replace(/\\n/g, "\n");
  if (clientEmail && privateKey) {
    initializeApp({ credential: cert({ projectId, clientEmail, privateKey }) });
  } else {
    initializeApp({ projectId });
  }
}
const db = getFirestore();

const args = process.argv.slice(2);
const DRY_RUN = args.includes("--dry-run");
const FORCE = args.includes("--force");

interface TermSeed {
  termEn: string; termHi: string; pronunciation: string; origin: string;
  category: string; definitionEn: string; definitionHi: string;
  exampleEn: string; exampleHi: string; relatedTerms: string[];
  relatedSections: string[]; source: string;
}

const terms: TermSeed[] = [
  // Criminal Law
  { termEn: "FIR", termHi: "प्रथम सूचना रिपोर्ट", pronunciation: "eff-eye-aar", origin: "English", category: "Criminal Law", definitionEn: "First Information Report — the written document prepared by police when they receive information about a cognizable offence. It is the first step in criminal proceedings.", definitionHi: "प्रथम सूचना रिपोर्ट — पुलिस द्वारा संज्ञेय अपराध की सूचना प्राप्त होने पर तैयार किया जाने वाला लिखित दस्तावेज। यह आपराधिक कार्यवाही का पहला कदम है।", exampleEn: "The victim filed an FIR at the nearest police station after the theft.", exampleHi: "पीड़ित ने चोरी के बाद निकटतम पुलिस स्टेशन में FIR दर्ज कराई।", relatedTerms: ["Cognizable Offence", "Chargesheet", "NCR"], relatedSections: ["S.173 BNSS"], source: "Indian Legal Dictionary" },
  { termEn: "Bail", termHi: "ज़मानत", pronunciation: "bayl", origin: "English", category: "Criminal Law", definitionEn: "The temporary release of an accused person awaiting trial, sometimes on condition that a sum of money is lodged to guarantee their appearance in court.", definitionHi: "मुकदमे की प्रतीक्षा कर रहे आरोपी व्यक्ति की अस्थायी रिहाई, कभी-कभी इस शर्त पर कि अदालत में उपस्थिति की गारंटी के लिए एक राशि जमा की जाए।", exampleEn: "The accused was granted bail by the Sessions Court.", exampleHi: "आरोपी को सत्र न्यायालय ने ज़मानत दी।", relatedTerms: ["Anticipatory Bail", "Surety", "Bond"], relatedSections: ["S.478-484 BNSS"], source: "Black's Law Dictionary" },
  { termEn: "Cognizable Offence", termHi: "संज्ञेय अपराध", pronunciation: "kog-ni-zuh-bl", origin: "English", category: "Criminal Law", definitionEn: "An offence in which the police can arrest without a warrant, register an FIR, and begin investigation without permission from a magistrate.", definitionHi: "वह अपराध जिसमें पुलिस बिना वारंट के गिरफ्तार कर सकती है, FIR दर्ज कर सकती है और मजिस्ट्रेट की अनुमति के बिना जांच शुरू कर सकती है।", exampleEn: "Murder is a cognizable offence, so police can arrest the suspect immediately.", exampleHi: "हत्या एक संज्ञेय अपराध है, इसलिए पुलिस संदिग्ध को तुरंत गिरफ्तार कर सकती है।", relatedTerms: ["Non-Cognizable Offence", "FIR", "Warrant"], relatedSections: ["S.2(c) BNSS", "First Schedule BNSS"], source: "Indian Legal Dictionary" },
  { termEn: "Anticipatory Bail", termHi: "अग्रिम ज़मानत", pronunciation: "an-tis-ip-uh-tor-ee bayl", origin: "English", category: "Criminal Law", definitionEn: "A direction by the court that if a person is arrested on accusation of a non-bailable offence, they shall be released on bail. Applied for before actual arrest.", definitionHi: "न्यायालय द्वारा एक निर्देश कि यदि किसी व्यक्ति को गैर-ज़मानती अपराध के आरोप में गिरफ्तार किया जाता है, तो उसे ज़मानत पर रिहा किया जाएगा। वास्तविक गिरफ्तारी से पहले आवेदन किया जाता है।", exampleEn: "Fearing arrest, the businessman applied for anticipatory bail in the High Court.", exampleHi: "गिरफ्तारी की आशंका से व्यापारी ने उच्च न्यायालय में अग्रिम ज़मानत की अर्जी दी।", relatedTerms: ["Bail", "Non-Bailable Offence", "High Court"], relatedSections: ["S.482 BNSS"], source: "Black's Law Dictionary" },
  { termEn: "Chargesheet", termHi: "आरोप पत्र", pronunciation: "chahrj-sheet", origin: "English", category: "Criminal Law", definitionEn: "A formal document prepared by the police after completing investigation, filed in court listing the accused, offences, evidence, and witnesses.", definitionHi: "पुलिस द्वारा जांच पूरी करने के बाद तैयार किया गया औपचारिक दस्तावेज, जो अदालत में आरोपी, अपराधों, साक्ष्यों और गवाहों की सूची के साथ दायर किया जाता है।", exampleEn: "Police filed a chargesheet within 90 days as required by law.", exampleHi: "पुलिस ने कानून की आवश्यकता अनुसार 90 दिनों के भीतर आरोप पत्र दायर किया।", relatedTerms: ["FIR", "Investigation", "Prosecution"], relatedSections: ["S.193 BNSS"], source: "Indian Legal Dictionary" },
  { termEn: "Summons", termHi: "समन", pronunciation: "sum-unz", origin: "Latin", category: "Criminal Law", definitionEn: "An official order issued by a court or magistrate requiring a person to appear before the court at a specified date and time.", definitionHi: "न्यायालय या मजिस्ट्रेट द्वारा जारी एक आधिकारिक आदेश जिसमें किसी व्यक्ति को निर्दिष्ट तिथि और समय पर न्यायालय के समक्ष उपस्थित होने की आवश्यकता होती है।", exampleEn: "The court issued a summons to the witness to appear for testimony.", exampleHi: "न्यायालय ने गवाह को गवाही के लिए उपस्थित होने हेतु समन जारी किया।", relatedTerms: ["Warrant", "Subpoena", "Notice"], relatedSections: ["S.64-70 BNSS"], source: "Black's Law Dictionary" },
  { termEn: "Warrant", termHi: "वारंट", pronunciation: "wor-uhnt", origin: "English", category: "Criminal Law", definitionEn: "A written order issued by a judge or magistrate authorizing police to make an arrest, search premises, or carry out some other action.", definitionHi: "किसी न्यायाधीश या मजिस्ट्रेट द्वारा जारी लिखित आदेश जो पुलिस को गिरफ्तारी करने, परिसर की तलाशी लेने, या कोई अन्य कार्रवाई करने का अधिकार देता है।", exampleEn: "The judge issued a search warrant for the suspect's residence.", exampleHi: "न्यायाधीश ने संदिग्ध के निवास के लिए तलाशी वारंट जारी किया।", relatedTerms: ["Arrest", "Search", "Summons"], relatedSections: ["S.71-82 BNSS"], source: "Black's Law Dictionary" },
  { termEn: "Remand", termHi: "रिमांड", pronunciation: "ri-mahnd", origin: "English", category: "Criminal Law", definitionEn: "The act of sending an accused person back into custody while awaiting trial. Can be judicial (jail) or police custody (for investigation).", definitionHi: "मुकदमे की प्रतीक्षा करते हुए आरोपी व्यक्ति को वापस हिरासत में भेजने की कार्रवाई। यह न्यायिक (जेल) या पुलिस हिरासत (जांच के लिए) हो सकती है।", exampleEn: "The court sent the accused on 14-day judicial remand.", exampleHi: "न्यायालय ने आरोपी को 14 दिन की न्यायिक रिमांड पर भेजा।", relatedTerms: ["Custody", "Bail", "Judicial Remand"], relatedSections: ["S.187 BNSS"], source: "Indian Legal Dictionary" },
  { termEn: "Acquittal", termHi: "बरी", pronunciation: "uh-kwit-ul", origin: "English", category: "Criminal Law", definitionEn: "A judgment that a person is not guilty of the crime with which they have been charged. The accused is set free from criminal liability.", definitionHi: "एक निर्णय कि व्यक्ति उस अपराध का दोषी नहीं है जिसका उस पर आरोप लगाया गया था। आरोपी को आपराधिक दायित्व से मुक्त किया जाता है।", exampleEn: "After examining the evidence, the court ordered the acquittal of the accused.", exampleHi: "साक्ष्यों की जांच के बाद, न्यायालय ने आरोपी को बरी करने का आदेश दिया।", relatedTerms: ["Conviction", "Verdict", "Discharge"], relatedSections: ["S.281 BNSS"], source: "Black's Law Dictionary" },
  { termEn: "Conviction", termHi: "दोषसिद्धि", pronunciation: "kun-vik-shun", origin: "Latin", category: "Criminal Law", definitionEn: "A formal declaration by a court that a person is found guilty of a criminal offence. It results in sentencing.", definitionHi: "न्यायालय द्वारा औपचारिक घोषणा कि व्यक्ति आपराधिक अपराध का दोषी पाया गया है। इसके परिणामस्वरूप सज़ा सुनाई जाती है।", exampleEn: "The conviction carried a sentence of five years imprisonment.", exampleHi: "दोषसिद्धि में पांच वर्ष कारावास की सज़ा सुनाई गई।", relatedTerms: ["Acquittal", "Sentence", "Appeal"], relatedSections: ["S.283 BNSS"], source: "Black's Law Dictionary" },
  // Constitutional Law
  { termEn: "Fundamental Rights", termHi: "मौलिक अधिकार", pronunciation: "fun-duh-men-tul ryts", origin: "English", category: "Constitutional Law", definitionEn: "Basic rights guaranteed to every citizen of India under Part III of the Constitution (Articles 12-35). These include right to equality, freedom, against exploitation, religion, culture, and constitutional remedies.", definitionHi: "भारत के संविधान के भाग III (अनुच्छेद 12-35) के तहत प्रत्येक नागरिक को गारंटीकृत बुनियादी अधिकार। इनमें समानता, स्वतंत्रता, शोषण के विरुद्ध, धर्म, संस्कृति और संवैधानिक उपचार का अधिकार शामिल है।", exampleEn: "The right to free speech is a Fundamental Right under Article 19(1)(a).", exampleHi: "बोलने की स्वतंत्रता अनुच्छेद 19(1)(a) के तहत एक मौलिक अधिकार है।", relatedTerms: ["Directive Principles", "Writ Petition", "Article 21"], relatedSections: ["Articles 12-35, Constitution of India"], source: "Indian Legal Dictionary" },
  { termEn: "Writ Petition", termHi: "रिट याचिका", pronunciation: "rit peh-tish-un", origin: "English", category: "Constitutional Law", definitionEn: "A formal written order issued by a High Court or Supreme Court under Articles 226 or 32 of the Constitution. Five types: Habeas Corpus, Mandamus, Certiorari, Prohibition, Quo Warranto.", definitionHi: "संविधान के अनुच्छेद 226 या 32 के तहत उच्च न्यायालय या सर्वोच्च न्यायालय द्वारा जारी एक औपचारिक लिखित आदेश। पांच प्रकार: बंदी प्रत्यक्षीकरण, परमादेश, उत्प्रेषण, निषेध, अधिकार पृच्छा।", exampleEn: "She filed a writ petition under Article 226 challenging the government order.", exampleHi: "उसने सरकारी आदेश को चुनौती देते हुए अनुच्छेद 226 के तहत रिट याचिका दायर की।", relatedTerms: ["Habeas Corpus", "Mandamus", "PIL"], relatedSections: ["Article 32, 226 Constitution of India"], source: "Black's Law Dictionary" },
  { termEn: "Habeas Corpus", termHi: "बंदी प्रत्यक्षीकरण", pronunciation: "hay-bee-us kor-pus", origin: "Latin", category: "Constitutional Law", definitionEn: "A writ requiring a person under arrest or detention to be brought before a court. It safeguards against unlawful detention and ensures the right to personal liberty.", definitionHi: "एक रिट जिसमें गिरफ्तार या हिरासत में रखे गए व्यक्ति को न्यायालय के समक्ष प्रस्तुत करने की आवश्यकता होती है। यह गैरकानूनी हिरासत से सुरक्षा करती है।", exampleEn: "The family filed a habeas corpus petition when the police detained him without charges.", exampleHi: "जब पुलिस ने बिना आरोप के उसे हिरासत में रखा तो परिवार ने बंदी प्रत्यक्षीकरण याचिका दायर की।", relatedTerms: ["Writ Petition", "Personal Liberty", "Article 21"], relatedSections: ["Article 32, 226 Constitution"], source: "Black's Law Dictionary" },
  { termEn: "PIL", termHi: "जनहित याचिका", pronunciation: "pee-eye-ell", origin: "English", category: "Constitutional Law", definitionEn: "Public Interest Litigation — a legal action initiated in a court of law for the enforcement of public interest. Any citizen can file it on behalf of the affected public.", definitionHi: "जनहित याचिका — जनहित के प्रवर्तन के लिए न्यायालय में शुरू की गई कानूनी कार्रवाई। कोई भी नागरिक प्रभावित जनता की ओर से इसे दायर कर सकता है।", exampleEn: "An NGO filed a PIL seeking better air quality measures in Delhi.", exampleHi: "एक एनजीओ ने दिल्ली में बेहतर वायु गुणवत्ता उपायों की मांग करते हुए जनहित याचिका दायर की।", relatedTerms: ["Writ Petition", "Supreme Court", "Article 32"], relatedSections: ["Article 32 Constitution of India"], source: "Indian Legal Dictionary" },
  { termEn: "Suo Motu", termHi: "स्वप्रेरणा", pronunciation: "soo-oh moh-too", origin: "Latin", category: "Constitutional Law", definitionEn: "An action taken by a court on its own motion without any request from the parties involved. Courts may take suo motu cognizance of matters of public importance.", definitionHi: "किसी भी पक्ष के अनुरोध के बिना न्यायालय द्वारा अपनी स्वयं की प्रेरणा पर की गई कार्रवाई। न्यायालय सार्वजनिक महत्व के मामलों का स्वप्रेरणा से संज्ञान ले सकते हैं।", exampleEn: "The Supreme Court took suo motu cognizance of the migrant worker crisis.", exampleHi: "सर्वोच्च न्यायालय ने प्रवासी श्रमिक संकट का स्वप्रेरणा से संज्ञान लिया।", relatedTerms: ["PIL", "Cognizance", "Judicial Review"], relatedSections: ["Article 32, 142 Constitution"], source: "Black's Law Dictionary" },
  { termEn: "Mandamus", termHi: "परमादेश", pronunciation: "man-day-mus", origin: "Latin", category: "Constitutional Law", definitionEn: "A judicial writ commanding a public authority or lower court to perform a mandatory duty. It literally means 'we command'.", definitionHi: "एक न्यायिक रिट जो किसी सार्वजनिक प्राधिकरण या निचली अदालत को अनिवार्य कर्तव्य निभाने का आदेश देती है। इसका शाब्दिक अर्थ है 'हम आदेश देते हैं'।", exampleEn: "The court issued a mandamus directing the municipality to repair the roads.", exampleHi: "न्यायालय ने नगरपालिका को सड़कों की मरम्मत करने का परमादेश जारी किया।", relatedTerms: ["Writ Petition", "Certiorari", "Quo Warranto"], relatedSections: ["Article 32, 226 Constitution"], source: "Black's Law Dictionary" },
  // Civil Law
  { termEn: "Decree", termHi: "डिक्री", pronunciation: "dih-kree", origin: "Latin", category: "Civil Law", definitionEn: "The formal expression of an adjudication by a civil court which conclusively determines the rights of the parties with regard to all or any of the matters in controversy.", definitionHi: "एक सिविल न्यायालय द्वारा न्यायनिर्णय की औपचारिक अभिव्यक्ति जो विवाद के सभी या किसी भी मामले के संबंध में पक्षों के अधिकारों को निर्णायक रूप से निर्धारित करती है।", exampleEn: "The court passed a decree in favour of the plaintiff for recovery of damages.", exampleHi: "न्यायालय ने वादी के पक्ष में हर्जाने की वसूली के लिए डिक्री पारित की।", relatedTerms: ["Judgment", "Order", "Execution"], relatedSections: ["S.2(2) CPC, O.20 CPC"], source: "Black's Law Dictionary" },
  { termEn: "Injunction", termHi: "निषेधाज्ञा", pronunciation: "in-junk-shun", origin: "Latin", category: "Civil Law", definitionEn: "A court order requiring a party to do or refrain from doing a specific act. Can be temporary (interim) or permanent.", definitionHi: "एक न्यायालय आदेश जिसमें किसी पक्ष को कोई विशिष्ट कार्य करने या उससे बचने की आवश्यकता होती है। यह अस्थायी (अंतरिम) या स्थायी हो सकती है।", exampleEn: "The court granted an injunction preventing the builder from demolishing the structure.", exampleHi: "न्यायालय ने बिल्डर को संरचना ध्वस्त करने से रोकने के लिए निषेधाज्ञा दी।", relatedTerms: ["Stay Order", "Restraining Order", "Specific Relief"], relatedSections: ["S.36-42 Specific Relief Act"], source: "Black's Law Dictionary" },
  { termEn: "Affidavit", termHi: "शपथ पत्र", pronunciation: "af-ih-day-vit", origin: "Latin", category: "Civil Law", definitionEn: "A written statement confirmed by oath or affirmation, for use as evidence in court. Making false statements in an affidavit constitutes perjury.", definitionHi: "शपथ या प्रतिज्ञान द्वारा पुष्टि किया गया लिखित बयान, जो न्यायालय में साक्ष्य के रूप में उपयोग किया जाता है। शपथ पत्र में झूठा बयान देना मिथ्या शपथ है।", exampleEn: "The applicant submitted an affidavit stating his income details.", exampleHi: "आवेदक ने अपनी आय का विवरण बताते हुए शपथ पत्र प्रस्तुत किया।", relatedTerms: ["Oath", "Notarization", "Evidence"], relatedSections: ["O.19 CPC, S.139 BSA"], source: "Black's Law Dictionary" },
  { termEn: "Limitation Period", termHi: "परिसीमा अवधि", pronunciation: "lim-ih-tay-shun", origin: "English", category: "Civil Law", definitionEn: "The maximum time after an event within which legal proceedings may be initiated. After this period expires, the claim becomes time-barred.", definitionHi: "किसी घटना के बाद अधिकतम समय जिसके भीतर कानूनी कार्यवाही शुरू की जा सकती है। इस अवधि की समाप्ति के बाद, दावा समय-बाधित हो जाता है।", exampleEn: "The limitation period for filing a civil suit for recovery of money is 3 years.", exampleHi: "धन की वसूली के लिए सिविल मुकदमा दायर करने की परिसीमा अवधि 3 वर्ष है।", relatedTerms: ["Time-Barred", "Prescription", "Condonation of Delay"], relatedSections: ["Limitation Act, 1963"], source: "Indian Legal Dictionary" },
  { termEn: "Caveat", termHi: "कैवीट", pronunciation: "kav-ee-at", origin: "Latin", category: "Civil Law", definitionEn: "A notice filed by a person in court to ensure that no order is passed in a matter without giving them a hearing first. Valid for 90 days.", definitionHi: "किसी व्यक्ति द्वारा न्यायालय में दायर एक सूचना ताकि यह सुनिश्चित किया जा सके कि पहले उन्हें सुनवाई दिए बिना कोई आदेश पारित न किया जाए। 90 दिनों के लिए वैध।", exampleEn: "The defendant filed a caveat to prevent any ex-parte order.", exampleHi: "प्रतिवादी ने किसी भी एकपक्षीय आदेश को रोकने के लिए कैवीट दायर किया।", relatedTerms: ["Ex-Parte", "Notice", "Hearing"], relatedSections: ["S.148A CPC"], source: "Black's Law Dictionary" },
  // Property Law
  { termEn: "Sale Deed", termHi: "बिक्री विलेख", pronunciation: "sayl deed", origin: "English", category: "Property Law", definitionEn: "A legal document that transfers ownership of immovable property from the seller to the buyer. Must be registered under the Registration Act.", definitionHi: "एक कानूनी दस्तावेज जो अचल संपत्ति का स्वामित्व विक्रेता से क्रेता को हस्तांतरित करता है। पंजीकरण अधिनियम के तहत इसका पंजीकरण अनिवार्य है।", exampleEn: "The sale deed was registered at the Sub-Registrar's office after payment of stamp duty.", exampleHi: "स्टांप शुल्क के भुगतान के बाद बिक्री विलेख उप-पंजीयक कार्यालय में पंजीकृत किया गया।", relatedTerms: ["Stamp Duty", "Registration", "Title"], relatedSections: ["S.54 Transfer of Property Act", "Registration Act 1908"], source: "Indian Legal Dictionary" },
  { termEn: "Power of Attorney", termHi: "मुख्तारनामा", pronunciation: "pow-er uv uh-tur-nee", origin: "English", category: "Property Law", definitionEn: "A legal document authorizing one person to act on behalf of another in legal or financial matters. Can be general or specific.", definitionHi: "एक कानूनी दस्तावेज जो एक व्यक्ति को कानूनी या वित्तीय मामलों में दूसरे की ओर से कार्य करने का अधिकार देता है। यह सामान्य या विशिष्ट हो सकता है।", exampleEn: "He executed a power of attorney in favour of his brother to sell the property.", exampleHi: "उसने संपत्ति बेचने के लिए अपने भाई के पक्ष में मुख्तारनामा निष्पादित किया।", relatedTerms: ["Agent", "Principal", "GPA"], relatedSections: ["Power of Attorney Act, 1882"], source: "Indian Legal Dictionary" },
  { termEn: "Encumbrance", termHi: "भार/ऋणभार", pronunciation: "en-kum-bruns", origin: "English", category: "Property Law", definitionEn: "A claim, lien, or liability attached to a property, such as a mortgage or unpaid taxes. An encumbrance certificate shows whether a property has any such charges.", definitionHi: "संपत्ति से जुड़ा दावा, ग्रहणाधिकार, या देनदारी, जैसे बंधक या अवैतनिक कर। भारमुक्ति प्रमाणपत्र दिखाता है कि संपत्ति पर ऐसा कोई भार है या नहीं।", exampleEn: "Before buying, always obtain an encumbrance certificate to verify the property is free of charges.", exampleHi: "खरीदने से पहले, हमेशा यह सत्यापित करने के लिए भारमुक्ति प्रमाणपत्र प्राप्त करें कि संपत्ति भारमुक्त है।", relatedTerms: ["Mortgage", "Lien", "Title Search"], relatedSections: ["Registration Act 1908"], source: "Black's Law Dictionary" },
  { termEn: "Mutation", termHi: "दाखिल-खारिज", pronunciation: "myoo-tay-shun", origin: "Latin", category: "Property Law", definitionEn: "The process of recording a change in ownership of property in the revenue records maintained by the local municipal body. Essential after purchase or inheritance.", definitionHi: "स्थानीय नगरपालिका निकाय द्वारा रखे गए राजस्व रिकॉर्ड में संपत्ति के स्वामित्व में परिवर्तन दर्ज करने की प्रक्रिया। खरीद या विरासत के बाद यह आवश्यक है।", exampleEn: "After the sale deed was registered, the buyer applied for mutation of property records.", exampleHi: "बिक्री विलेख के पंजीकरण के बाद, खरीदार ने संपत्ति रिकॉर्ड के दाखिल-खारिज के लिए आवेदन किया।", relatedTerms: ["Revenue Records", "Khata", "Sale Deed"], relatedSections: ["State Revenue Laws"], source: "Indian Legal Dictionary" },
  { termEn: "Stamp Duty", termHi: "स्टांप शुल्क", pronunciation: "stamp doo-tee", origin: "English", category: "Property Law", definitionEn: "A tax levied by the state government on legal documents, especially those related to the transfer of property. Rates vary by state.", definitionHi: "राज्य सरकार द्वारा कानूनी दस्तावेजों पर लगाया जाने वाला कर, विशेष रूप से संपत्ति हस्तांतरण से संबंधित। दरें राज्य के अनुसार भिन्न होती हैं।", exampleEn: "The stamp duty on property sale in Maharashtra is 5% of the transaction value.", exampleHi: "महाराष्ट्र में संपत्ति बिक्री पर स्टांप शुल्क लेनदेन मूल्य का 5% है।", relatedTerms: ["Registration", "Sale Deed", "Sub-Registrar"], relatedSections: ["Indian Stamp Act, 1899"], source: "Indian Legal Dictionary" },
  // Family Law
  { termEn: "Maintenance", termHi: "भरण-पोषण", pronunciation: "mayn-tuh-nuns", origin: "English", category: "Family Law", definitionEn: "Financial support that one spouse is required to pay to the other (or to children) during or after divorce proceedings. Also called alimony.", definitionHi: "वित्तीय सहायता जो एक पति/पत्नी को तलाक की कार्यवाही के दौरान या बाद में दूसरे (या बच्चों) को देनी होती है। इसे गुजारा भत्ता भी कहा जाता है।", exampleEn: "The wife was awarded Rs. 25,000 per month as maintenance.", exampleHi: "पत्नी को भरण-पोषण के रूप में प्रति माह 25,000 रुपये दिए गए।", relatedTerms: ["Alimony", "Divorce", "Custody"], relatedSections: ["S.125 BNSS", "Hindu Marriage Act S.24-25"], source: "Indian Legal Dictionary" },
  { termEn: "Divorce", termHi: "तलाक", pronunciation: "dih-vors", origin: "Latin", category: "Family Law", definitionEn: "The legal dissolution of a marriage by a court. In India, grounds include cruelty, desertion, adultery, mental disorder, and mutual consent.", definitionHi: "न्यायालय द्वारा विवाह का कानूनी विघटन। भारत में आधारों में क्रूरता, परित्याग, व्यभिचार, मानसिक विकार और आपसी सहमति शामिल हैं।", exampleEn: "The couple filed for divorce by mutual consent after a separation period of one year.", exampleHi: "दम्पति ने एक वर्ष की अलगाव अवधि के बाद आपसी सहमति से तलाक के लिए आवेदन किया।", relatedTerms: ["Maintenance", "Custody", "Separation"], relatedSections: ["S.13 Hindu Marriage Act", "S.2 Dissolution of Muslim Marriages Act"], source: "Indian Legal Dictionary" },
  { termEn: "Dowry", termHi: "दहेज", pronunciation: "dow-ree", origin: "English", category: "Family Law", definitionEn: "Any property or valuable security given or demanded as consideration for marriage. Giving and taking dowry is a criminal offence in India.", definitionHi: "विवाह के प्रतिफल के रूप में दी या मांगी गई कोई भी संपत्ति या मूल्यवान प्रतिभूति। भारत में दहेज लेना और देना आपराधिक अपराध है।", exampleEn: "Demanding a car as dowry from the bride's family is a criminal offence under the Dowry Prohibition Act.", exampleHi: "दुल्हन के परिवार से दहेज के रूप में कार मांगना दहेज निषेध अधिनियम के तहत आपराधिक अपराध है।", relatedTerms: ["Streedhan", "Domestic Violence", "S.498A"], relatedSections: ["Dowry Prohibition Act, 1961", "S.80-81 BNS"], source: "Indian Legal Dictionary" },
  { termEn: "Custody", termHi: "अभिरक्षा", pronunciation: "kus-tuh-dee", origin: "Latin", category: "Family Law", definitionEn: "The legal right to care for and make decisions about a child after divorce or separation. Can be sole or joint custody.", definitionHi: "तलाक या अलगाव के बाद बच्चे की देखभाल और उसके बारे में निर्णय लेने का कानूनी अधिकार। यह एकल या संयुक्त अभिरक्षा हो सकती है।", exampleEn: "The mother was granted custody of the minor children, with visitation rights for the father.", exampleHi: "माँ को नाबालिग बच्चों की अभिरक्षा दी गई, पिता को मिलने का अधिकार दिया गया।", relatedTerms: ["Guardian", "Maintenance", "Visitation"], relatedSections: ["Guardians and Wards Act, 1890", "Hindu Minority and Guardianship Act"], source: "Indian Legal Dictionary" },
  // Corporate Law
  { termEn: "Memorandum of Understanding", termHi: "समझौता ज्ञापन", pronunciation: "mem-oh-ran-dum", origin: "Latin", category: "Corporate Law", definitionEn: "A formal agreement between two or more parties that outlines the terms and details of an understanding. It is not typically legally binding unless expressed so.", definitionHi: "दो या अधिक पक्षों के बीच एक औपचारिक समझौता जो एक समझ की शर्तों और विवरणों की रूपरेखा तैयार करता है।", exampleEn: "The two companies signed an MoU to collaborate on renewable energy projects.", exampleHi: "दोनों कंपनियों ने नवीकरणीय ऊर्जा परियोजनाओं पर सहयोग करने के लिए समझौता ज्ञापन पर हस्ताक्षर किए।", relatedTerms: ["Contract", "Agreement", "Letter of Intent"], relatedSections: ["Indian Contract Act, 1872"], source: "Black's Law Dictionary" },
  { termEn: "Winding Up", termHi: "समापन", pronunciation: "wynd-ing up", origin: "English", category: "Corporate Law", definitionEn: "The process of dissolving a company by selling its assets, paying off debts, and distributing remaining funds to shareholders.", definitionHi: "किसी कंपनी की संपत्ति बेचकर, ऋण चुकाकर, और शेष धन शेयरधारकों को वितरित करके उसे भंग करने की प्रक्रिया।", exampleEn: "The NCLT ordered the winding up of the company due to persistent default in debt repayment.", exampleHi: "ऋण चुकौती में लगातार चूक के कारण NCLT ने कंपनी के समापन का आदेश दिया।", relatedTerms: ["Insolvency", "Liquidation", "NCLT"], relatedSections: ["Companies Act 2013, IBC 2016"], source: "Indian Legal Dictionary" },
  // Consumer Law
  { termEn: "Deficiency in Service", termHi: "सेवा में कमी", pronunciation: "deh-fish-en-see", origin: "English", category: "Consumer Law", definitionEn: "Any fault, imperfection, shortcoming, or inadequacy in the quality, nature, and manner of performance required by law or agreed upon in a contract of service.", definitionHi: "सेवा अनुबंध में कानून द्वारा अपेक्षित या सहमत प्रदर्शन की गुणवत्ता, प्रकृति और तरीके में कोई भी दोष, अपूर्णता, कमी या अपर्याप्तता।", exampleEn: "The insurance company's denial of a valid claim was held to be a deficiency in service.", exampleHi: "बीमा कंपनी द्वारा वैध दावे को अस्वीकार करना सेवा में कमी माना गया।", relatedTerms: ["Consumer Complaint", "Unfair Trade Practice", "Compensation"], relatedSections: ["S.2(11) Consumer Protection Act 2019"], source: "Indian Legal Dictionary" },
  { termEn: "Unfair Trade Practice", termHi: "अनुचित व्यापार व्यवहार", pronunciation: "un-fair trayd", origin: "English", category: "Consumer Law", definitionEn: "A trade practice that uses deceptive methods like false representation, misleading advertisements, or fraudulent schemes to promote sale of goods or services.", definitionHi: "एक व्यापार व्यवहार जो वस्तुओं या सेवाओं की बिक्री को बढ़ावा देने के लिए झूठे प्रतिनिधित्व, भ्रामक विज्ञापनों या धोखाधड़ी योजनाओं जैसी भ्रामक विधियों का उपयोग करता है।", exampleEn: "Advertising a product with fake discounts is an unfair trade practice.", exampleHi: "नकली छूट के साथ उत्पाद का विज्ञापन करना एक अनुचित व्यापार व्यवहार है।", relatedTerms: ["Consumer Complaint", "MRP", "CCPA"], relatedSections: ["S.2(47) Consumer Protection Act 2019"], source: "Indian Legal Dictionary" },
  // Labour Law
  { termEn: "Gratuity", termHi: "उपदान", pronunciation: "gruh-too-ih-tee", origin: "Latin", category: "Labour Law", definitionEn: "A lump sum payment made by an employer to an employee on termination of employment after completing at least 5 years of service. Calculated at 15 days wages per year of service.", definitionHi: "कम से कम 5 वर्ष की सेवा पूरी करने के बाद रोजगार समाप्ति पर नियोक्ता द्वारा कर्मचारी को किया जाने वाला एकमुश्त भुगतान। सेवा के प्रति वर्ष 15 दिन के वेतन पर गणना।", exampleEn: "After 10 years of service, she received gratuity of Rs. 3 lakhs upon retirement.", exampleHi: "10 वर्ष की सेवा के बाद, उसे सेवानिवृत्ति पर 3 लाख रुपये का उपदान मिला।", relatedTerms: ["Provident Fund", "Retirement", "Termination"], relatedSections: ["Payment of Gratuity Act, 1972"], source: "Indian Legal Dictionary" },
  { termEn: "Retrenchment", termHi: "छंटनी", pronunciation: "ree-trench-ment", origin: "English", category: "Labour Law", definitionEn: "The termination of a worker's service by the employer for any reason other than disciplinary action. The employer must give one month's notice or wages in lieu.", definitionHi: "अनुशासनात्मक कार्रवाई के अलावा किसी भी कारण से नियोक्ता द्वारा किसी कर्मचारी की सेवा समाप्त करना। नियोक्ता को एक महीने का नोटिस या बदले में वेतन देना होगा।", exampleEn: "The factory retrenched 200 workers due to economic slowdown.", exampleHi: "आर्थिक मंदी के कारण कारखाने ने 200 श्रमिकों की छंटनी की।", relatedTerms: ["Lay-off", "Termination", "Industrial Dispute"], relatedSections: ["S.25F Industrial Disputes Act"], source: "Indian Legal Dictionary" },
  { termEn: "Provident Fund", termHi: "भविष्य निधि", pronunciation: "prov-ih-dent", origin: "English", category: "Labour Law", definitionEn: "A compulsory savings scheme where both employer and employee contribute 12% of basic salary. The accumulated amount is paid on retirement or resignation.", definitionHi: "एक अनिवार्य बचत योजना जहां नियोक्ता और कर्मचारी दोनों मूल वेतन का 12% योगदान करते हैं। संचित राशि सेवानिवृत्ति या इस्तीफे पर दी जाती है।", exampleEn: "Both employer and employee contribute 12% of basic salary to the EPF.", exampleHi: "नियोक्ता और कर्मचारी दोनों मूल वेतन का 12% EPF में योगदान करते हैं।", relatedTerms: ["EPFO", "Pension", "Gratuity"], relatedSections: ["EPF & MP Act, 1952"], source: "Indian Legal Dictionary" },
  // Additional important terms
  { termEn: "Certiorari", termHi: "उत्प्रेषण", pronunciation: "sur-shee-oh-rar-ee", origin: "Latin", category: "Constitutional Law", definitionEn: "A writ by which a superior court quashes the decision of an inferior court or tribunal that has acted beyond its jurisdiction or in violation of natural justice.", definitionHi: "एक रिट जिसके द्वारा उच्च न्यायालय निचली अदालत या न्यायाधिकरण के उस निर्णय को रद्द करता है जिसने अपने अधिकार क्षेत्र से परे कार्य किया है।", exampleEn: "The High Court issued certiorari quashing the tribunal's order passed without jurisdiction.", exampleHi: "उच्च न्यायालय ने अधिकार क्षेत्र के बिना पारित न्यायाधिकरण के आदेश को रद्द करते हुए उत्प्रेषण जारी किया।", relatedTerms: ["Writ Petition", "Mandamus", "Judicial Review"], relatedSections: ["Article 226 Constitution"], source: "Black's Law Dictionary" },
  { termEn: "Quo Warranto", termHi: "अधिकार पृच्छा", pronunciation: "kwoh wuh-ran-toh", origin: "Latin", category: "Constitutional Law", definitionEn: "A writ that challenges the legal authority of a person holding a public office. It asks 'by what authority' do you hold this position.", definitionHi: "एक रिट जो किसी सार्वजनिक पद धारण करने वाले व्यक्ति के कानूनी अधिकार को चुनौती देती है। यह पूछती है 'किस अधिकार से' आप यह पद धारण करते हैं।", exampleEn: "A quo warranto petition was filed questioning the appointment of the university vice-chancellor.", exampleHi: "विश्वविद्यालय के कुलपति की नियुक्ति पर सवाल उठाते हुए अधिकार पृच्छा याचिका दायर की गई।", relatedTerms: ["Writ Petition", "Public Office", "Mandamus"], relatedSections: ["Article 226 Constitution"], source: "Black's Law Dictionary" },
  { termEn: "Specific Performance", termHi: "विनिर्दिष्ट पालन", pronunciation: "speh-sif-ik per-for-muns", origin: "English", category: "Civil Law", definitionEn: "An equitable remedy where the court orders a party to perform their obligations under a contract, typically for sale of immovable property.", definitionHi: "एक साम्यिक उपचार जहां न्यायालय किसी पक्ष को अनुबंध के तहत अपने दायित्वों को पूरा करने का आदेश देता है, आमतौर पर अचल संपत्ति की बिक्री के लिए।", exampleEn: "The court ordered specific performance of the agreement to sell the land.", exampleHi: "न्यायालय ने भूमि बेचने के समझौते के विनिर्दिष्ट पालन का आदेश दिया।", relatedTerms: ["Injunction", "Contract", "Breach"], relatedSections: ["S.10-25 Specific Relief Act, 1963"], source: "Black's Law Dictionary" },
  { termEn: "Perjury", termHi: "मिथ्या शपथ", pronunciation: "pur-juh-ree", origin: "Latin", category: "Criminal Law", definitionEn: "The offence of deliberately making false statements under oath or affirmation in judicial proceedings.", definitionHi: "न्यायिक कार्यवाही में शपथ या प्रतिज्ञान के तहत जानबूझकर झूठा बयान देने का अपराध।", exampleEn: "The witness was charged with perjury for lying under oath.", exampleHi: "शपथ के तहत झूठ बोलने के लिए गवाह पर मिथ्या शपथ का आरोप लगाया गया।", relatedTerms: ["Oath", "Affidavit", "Contempt"], relatedSections: ["S.229 BNS"], source: "Black's Law Dictionary" },
  { termEn: "Defamation", termHi: "मानहानि", pronunciation: "def-uh-may-shun", origin: "Latin", category: "Criminal Law", definitionEn: "Making or publishing a false statement that damages the reputation of an identifiable person. Can be civil (damages) or criminal (imprisonment).", definitionHi: "किसी पहचान योग्य व्यक्ति की प्रतिष्ठा को नुकसान पहुंचाने वाला झूठा बयान बनाना या प्रकाशित करना। यह सिविल (हर्जाना) या आपराधिक (कारावास) हो सकता है।", exampleEn: "The politician filed a defamation suit against the newspaper for the false article.", exampleHi: "राजनेता ने झूठे लेख के लिए अखबार के खिलाफ मानहानि का मुकदमा दायर किया।", relatedTerms: ["Libel", "Slander", "Reputation"], relatedSections: ["S.356 BNS"], source: "Black's Law Dictionary" },
  { termEn: "Arbitration", termHi: "मध्यस्थता", pronunciation: "ahr-bih-tray-shun", origin: "Latin", category: "Civil Law", definitionEn: "A method of alternative dispute resolution where parties agree to have their dispute decided by an independent third party (arbitrator) instead of going to court.", definitionHi: "वैकल्पिक विवाद समाधान की एक विधि जहां पक्ष अदालत जाने के बजाय एक स्वतंत्र तृतीय पक्ष (मध्यस्थ) द्वारा अपने विवाद का निपटारा कराने पर सहमत होते हैं।", exampleEn: "The contract contained an arbitration clause requiring disputes to be settled in Mumbai.", exampleHi: "अनुबंध में एक मध्यस्थता खंड था जिसमें विवादों को मुंबई में निपटाने की आवश्यकता थी।", relatedTerms: ["Mediation", "Conciliation", "ADR"], relatedSections: ["Arbitration and Conciliation Act, 1996"], source: "Black's Law Dictionary" },
  { termEn: "Streedhan", termHi: "स्त्रीधन", pronunciation: "stree-dhan", origin: "Sanskrit", category: "Family Law", definitionEn: "Property belonging to a woman, including gifts received before, during, and after marriage from parents, relatives, or husband's family. It is her absolute property.", definitionHi: "महिला की संपत्ति, जिसमें माता-पिता, रिश्तेदारों या पति के परिवार से विवाह से पहले, दौरान और बाद में प्राप्त उपहार शामिल हैं। यह उसकी पूर्ण संपत्ति है।", exampleEn: "The gold jewellery given to the bride at the wedding is her streedhan and cannot be claimed by the in-laws.", exampleHi: "शादी में दुल्हन को दिए गए सोने के आभूषण उसका स्त्रीधन हैं और ससुराल वाले उस पर दावा नहीं कर सकते।", relatedTerms: ["Dowry", "Inheritance", "Hindu Succession"], relatedSections: ["Hindu Succession Act, 1956"], source: "Indian Legal Dictionary" },
  { termEn: "Cheque Bounce", termHi: "चेक बाउंस", pronunciation: "chek bowns", origin: "English", category: "Criminal Law", definitionEn: "When a cheque is returned unpaid by the bank due to insufficient funds or other reasons. It is a criminal offence punishable with imprisonment up to 2 years.", definitionHi: "जब अपर्याप्त धनराशि या अन्य कारणों से बैंक द्वारा चेक अवैतनिक लौटाया जाता है। यह 2 वर्ष तक के कारावास से दंडनीय आपराधिक अपराध है।", exampleEn: "The creditor filed a cheque bounce case under Section 138 of the NI Act.", exampleHi: "लेनदार ने NI अधिनियम की धारा 138 के तहत चेक बाउंस का मामला दर्ज किया।", relatedTerms: ["Negotiable Instrument", "Dishonour", "Notice"], relatedSections: ["S.138 Negotiable Instruments Act, 1881"], source: "Indian Legal Dictionary" },
  { termEn: "Contempt of Court", termHi: "न्यायालय की अवमानना", pronunciation: "kun-tempt", origin: "English", category: "Constitutional Law", definitionEn: "An act of disrespect or disobedience towards a court of law. Can be civil (disobeying court orders) or criminal (scandalizing the court).", definitionHi: "न्यायालय के प्रति अनादर या अवज्ञा का कार्य। यह सिविल (न्यायालय के आदेशों की अवज्ञा) या आपराधिक (न्यायालय को बदनाम करना) हो सकता है।", exampleEn: "The company was held in contempt for not complying with the court order.", exampleHi: "न्यायालय के आदेश का पालन न करने पर कंपनी को अवमानना का दोषी ठहराया गया।", relatedTerms: ["Court Order", "Compliance", "Penalty"], relatedSections: ["Contempt of Courts Act, 1971", "Article 129 Constitution"], source: "Indian Legal Dictionary" },
  { termEn: "Plea Bargaining", termHi: "अभिवचन सौदेबाज़ी", pronunciation: "plee bahr-guh-ning", origin: "English", category: "Criminal Law", definitionEn: "A negotiation between the accused and the prosecution where the accused agrees to plead guilty to a lesser charge in exchange for a lighter sentence.", definitionHi: "आरोपी और अभियोजन पक्ष के बीच एक बातचीत जहां आरोपी हल्की सज़ा के बदले में कम आरोप का दोषी होने पर सहमत होता है।", exampleEn: "The accused opted for plea bargaining and received a reduced sentence.", exampleHi: "आरोपी ने अभिवचन सौदेबाज़ी का विकल्प चुना और कम सज़ा प्राप्त की।", relatedTerms: ["Guilty Plea", "Prosecution", "Sentence"], relatedSections: ["S.290-294 BNSS"], source: "Indian Legal Dictionary" },
  { termEn: "Locus Standi", termHi: "वाद-अधिकार", pronunciation: "loh-kus stan-dee", origin: "Latin", category: "Civil Law", definitionEn: "The right or capacity of a person to bring a legal action in court. A party must have sufficient connection to and harm from the matter to have standing.", definitionHi: "किसी व्यक्ति का न्यायालय में कानूनी कार्रवाई लाने का अधिकार या क्षमता। एक पक्ष को मामले से पर्याप्त संबंध और नुकसान होना चाहिए।", exampleEn: "The court dismissed the petition as the petitioner lacked locus standi.", exampleHi: "न्यायालय ने याचिका खारिज कर दी क्योंकि याचिकाकर्ता के पास वाद-अधिकार नहीं था।", relatedTerms: ["PIL", "Jurisdiction", "Standing"], relatedSections: ["CPC, Article 32"], source: "Black's Law Dictionary" },
  { termEn: "Res Judicata", termHi: "पूर्व न्याय", pronunciation: "rays joo-dih-kah-tuh", origin: "Latin", category: "Civil Law", definitionEn: "A matter that has been adjudicated by a competent court and cannot be relitigated between the same parties. It prevents the same case from being tried again.", definitionHi: "एक मामला जिसका सक्षम न्यायालय द्वारा निर्णय किया जा चुका है और समान पक्षों के बीच फिर से मुकदमा नहीं चलाया जा सकता।", exampleEn: "The second suit was barred by res judicata as the same issue was already decided.", exampleHi: "दूसरा वाद पूर्व न्याय से बाधित था क्योंकि उसी मुद्दे का पहले ही निर्णय किया जा चुका था।", relatedTerms: ["Estoppel", "Precedent", "Final Judgment"], relatedSections: ["S.11 CPC"], source: "Black's Law Dictionary" },
  { termEn: "Stay Order", termHi: "स्थगनादेश", pronunciation: "stay or-der", origin: "English", category: "Civil Law", definitionEn: "A court order that temporarily halts or suspends a judicial proceeding, enforcement of a judgment, or any action pending further proceedings.", definitionHi: "एक न्यायालय आदेश जो आगे की कार्यवाही तक अस्थायी रूप से न्यायिक कार्यवाही, निर्णय के प्रवर्तन या किसी कार्रवाई को रोकता या निलंबित करता है।", exampleEn: "The High Court granted a stay order on the demolition notice.", exampleHi: "उच्च न्यायालय ने विध्वंस नोटिस पर स्थगनादेश दिया।", relatedTerms: ["Injunction", "Interim Order", "Suspension"], relatedSections: ["O.39 CPC"], source: "Indian Legal Dictionary" },
  { termEn: "Cross-Examination", termHi: "जिरह", pronunciation: "kross ig-zam-ih-nay-shun", origin: "English", category: "Criminal Law", definitionEn: "The questioning of a witness by the opposing party during trial. Its purpose is to test the truthfulness and accuracy of the testimony given during examination-in-chief.", definitionHi: "मुकदमे के दौरान विरोधी पक्ष द्वारा गवाह से पूछताछ। इसका उद्देश्य मुख्य परीक्षा में दी गई गवाही की सच्चाई और सटीकता की जांच करना है।", exampleEn: "During cross-examination, the defense lawyer exposed contradictions in the witness's statement.", exampleHi: "जिरह के दौरान, बचाव पक्ष के वकील ने गवाह के बयान में विरोधाभासों को उजागर किया।", relatedTerms: ["Examination-in-Chief", "Witness", "Testimony"], relatedSections: ["S.143 BSA"], source: "Indian Legal Dictionary" },
  { termEn: "Domestic Violence", termHi: "घरेलू हिंसा", pronunciation: "doh-mes-tik vy-oh-luns", origin: "English", category: "Family Law", definitionEn: "Any act of physical, sexual, verbal, emotional, or economic abuse by a family member or intimate partner. Women can seek protection orders under the DV Act.", definitionHi: "परिवार के सदस्य या अंतरंग साथी द्वारा शारीरिक, यौन, मौखिक, भावनात्मक या आर्थिक दुर्व्यवहार का कोई भी कार्य। महिलाएं DV अधिनियम के तहत सुरक्षा आदेश प्राप्त कर सकती हैं।", exampleEn: "She filed a complaint under the Domestic Violence Act seeking a protection order against her husband.", exampleHi: "उसने अपने पति के खिलाफ सुरक्षा आदेश की मांग करते हुए घरेलू हिंसा अधिनियम के तहत शिकायत दर्ज कराई।", relatedTerms: ["Protection Order", "Maintenance", "Streedhan"], relatedSections: ["Protection of Women from DV Act, 2005"], source: "Indian Legal Dictionary" },
  { termEn: "Non-Bailable Offence", termHi: "गैर-ज़मानती अपराध", pronunciation: "non-bay-luh-bl", origin: "English", category: "Criminal Law", definitionEn: "A serious offence where bail is not a matter of right but is granted at the discretion of the court. The accused must apply to the court for bail.", definitionHi: "एक गंभीर अपराध जहां ज़मानत अधिकार का मामला नहीं है बल्कि न्यायालय के विवेकाधिकार पर दी जाती है। आरोपी को ज़मानत के लिए न्यायालय में आवेदन करना होता है।", exampleEn: "Murder is a non-bailable offence, and the accused must seek bail from the court.", exampleHi: "हत्या एक गैर-ज़मानती अपराध है, और आरोपी को न्यायालय से ज़मानत लेनी होगी।", relatedTerms: ["Bail", "Cognizable Offence", "Anticipatory Bail"], relatedSections: ["First Schedule BNSS"], source: "Indian Legal Dictionary" },
];

async function main() {
  console.log(`\n📖 SatyaVera Dictionary Seeder`);
  console.log(`   Terms: ${terms.length}`);
  console.log(`   Mode:  ${DRY_RUN ? "DRY RUN" : "LIVE"}\n`);

  if (DRY_RUN) {
    const cats = new Map<string, number>();
    terms.forEach(t => cats.set(t.category, (cats.get(t.category) || 0) + 1));
    cats.forEach((count, cat) => console.log(`   ${cat}: ${count}`));
    console.log(`\n✅ Dry run complete. ${terms.length} terms would be seeded.`);
    return;
  }

  let created = 0, skipped = 0;
  const batch = db.batch();

  for (const term of terms) {
    const slug = term.termEn.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    const ref = db.collection("dictionaryEntries").doc(slug);
    const existing = await ref.get();

    if (existing.exists && !FORCE) {
      skipped++;
      continue;
    }

    batch.set(ref, {
      ...term,
      letter: term.termEn[0].toUpperCase(),
      createdAt: FieldValue.serverTimestamp(),
    });
    created++;
  }

  if (created > 0) {
    await batch.commit();
  }

  console.log(`✅ Done. Created: ${created}, Skipped: ${skipped}`);
}

main().catch(console.error);
