use serde_json::Value;

use crate::error::ApiError;

pub const LEGAL_SYSTEM_PROMPT: &str = r#"You are GandhiAI, an AI legal assistant built by SatyaVera for Indian citizens and advocates.

Core rules:
1. Provide legal information, not legal advice, and ask users to consult a qualified advocate for specific matters.
2. Cite specific Indian law sections when possible.
3. Use the Bharatiya Nyaya Sanhita, Bharatiya Nagarik Suraksha Sanhita, and Bharatiya Sakshya Adhiniyam for criminal law references.
4. Respond in the user's language when it is clear from the prompt.
"#;

pub fn validate_messages(messages: &[Value]) -> Result<(), ApiError> {
    if messages.is_empty() {
        return Err(ApiError::bad_request("Messages array must not be empty"));
    }

    for (index, message) in messages.iter().enumerate() {
        let object = message
            .as_object()
            .ok_or_else(|| ApiError::bad_request(format!("messages[{index}] must be an object")))?;
        let role = object.get("role").and_then(Value::as_str).ok_or_else(|| {
            ApiError::bad_request(format!(
                "messages[{index}].role is required and must be a string"
            ))
        })?;
        if !matches!(role, "user" | "assistant" | "system") {
            return Err(ApiError::bad_request(format!(
                "messages[{index}].role must be user, assistant, or system"
            )));
        }
        if object.get("content").is_none() && object.get("parts").is_none() {
            return Err(ApiError::bad_request(format!(
                "messages[{index}].content is required"
            )));
        }
    }
    Ok(())
}

pub fn fallback_chat_response(messages: &[Value]) -> String {
    let last_user_message = messages
        .iter()
        .rev()
        .find(|message| message.get("role").and_then(Value::as_str) == Some("user"))
        .and_then(extract_text)
        .unwrap_or_else(|| "your question".to_owned());

    format!(
        "{LEGAL_SYSTEM_PROMPT}\n\nI received: {last_user_message}\n\nThis Rust API endpoint is active. Configure the production AI provider in the Rust service environment to enable model-backed responses."
    )
}

pub fn generate_document(type_name: &str, details: &serde_json::Map<String, Value>) -> String {
    let title = details
        .get("title")
        .and_then(Value::as_str)
        .unwrap_or("Untitled legal document");
    let details_text = details
        .iter()
        .map(|(key, value)| format!("{key}: {}", value.as_str().unwrap_or_default()))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "{type_name}\n\nTitle: {title}\n\nDraft generated by SatyaVera Rust API.\n\nFacts and details:\n{details_text}\n\nLegal information disclaimer: this draft is informational and should be reviewed by a qualified advocate before use."
    )
}

fn extract_text(message: &Value) -> Option<String> {
    if let Some(content) = message.get("content").and_then(Value::as_str) {
        return Some(content.to_owned());
    }
    message
        .get("parts")
        .and_then(Value::as_array)
        .map(|parts| {
            parts
                .iter()
                .filter_map(|part| part.get("text").and_then(Value::as_str))
                .collect::<Vec<_>>()
                .join("")
        })
        .filter(|text| !text.is_empty())
}
